Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.define "jumpbox" do |jumpbox|
    jumpbox.vm.provider "virtualbox" do |vb|
      vb.name = "jumpbox"
      vb.cpus = 1
      vb.memory = 512
    end
    jumpbox.vm.hostname = "jumpbox"
    jumpbox.vm.network "private_network", ip: "192.168.56.10"
    jumpbox.vm.disk :disk, size: "10GB", name: "jumpbox-disk"
  end

  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.cpus = 1
      vb.memory = 2048
    end
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.11"
    server.vm.disk :disk, size: "20GB", name: "server-disk"
  end

  config.vm.define "node-0" do |node0|
    node0.vm.provider "virtualbox" do |vb|
      vb.name = "node-0"
      vb.cpus = 1
      vb.memory = 1024
    end
    node0.vm.hostname = "node-0"
    node0.vm.network "private_network", ip: "192.168.56.12"
    node0.vm.disk :disk, size: "20GB", name: "node-0-disk"
  end

  config.vm.define "node-1" do |node1|
    node1.vm.provider "virtualbox" do |vb|
      vb.name = "node-1"
      vb.cpus = 1
      vb.memory = 1024
    end
    node1.vm.hostname = "node-1"
    node1.vm.network "private_network", ip: "192.168.56.13"
    node1.vm.disk :disk, size: "20GB", name: "node-1-disk"
  end

end

