Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.hostname = "jumpbox"
  config.vm.provider "vmware_desktop" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
end
